/*
 *  openCook
 *  Copyright (C) 2026 olie.xdev <olie.xdeveloper@googlemail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.food.opencook.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local mirror of an extraction job. The primary key [jobId] is generated by the
 * client the moment a photo is taken, so a scan exists (and survives process
 * death) even while offline: it sits as "pending" until the upload worker can
 * reach the server, which then fills [serverJobId]. Offline-first by design.
 *
 * [resultDrainedAt] is the idempotency marker: once the server's recipes are
 * written into Room it is set, so the active poll and the fallback
 * [com.food.opencook.work.PollJobWorker] never create duplicate drafts.
 */
@Entity(tableName = "jobs")
data class JobEntity(
    @PrimaryKey val jobId: String,
    val localImagePath: String,
    /** Assigned by the server once the photo is uploaded; null while still queued. */
    val serverJobId: String? = null,
    val status: String,
    /** Coarse server stage key while processing (e.g. "reading_text"); null otherwise. */
    val stage: String? = null,
    val error: String? = null,
    val resultDrainedAt: Long? = null,
    /** Set when the user has seen/reviewed this finished scan, so the status strip clears. */
    val acknowledgedAt: Long? = null,
    val createdAt: Long,
    val updatedAt: Long,
)
