package com.food.opencook.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local mirror of an extraction job. The primary key [jobId] is generated by the
 * client the moment a photo is taken, so a scan exists (and survives process
 * death) even while offline: it sits as "pending" until the upload worker can
 * reach the server, which then fills [serverJobId]. Offline-first by design.
 *
 * [resultDrainedAt] is the idempotency marker: once the server's recipes are
 * written into Room it is set, so the active poll and the fallback
 * [com.food.opencook.work.PollJobWorker] never create duplicate drafts.
 */
@Entity(tableName = "jobs")
data class JobEntity(
    @PrimaryKey val jobId: String,
    val localImagePath: String,
    /** Assigned by the server once the photo is uploaded; null while still queued. */
    val serverJobId: String? = null,
    val status: String,
    /** Coarse server stage key while processing (e.g. "reading_text"); null otherwise. */
    val stage: String? = null,
    val error: String? = null,
    val resultDrainedAt: Long? = null,
    /** Set when the user has seen/reviewed this finished scan, so the status strip clears. */
    val acknowledgedAt: Long? = null,
    val createdAt: Long,
    val updatedAt: Long,
)
